spring:
  datasource:
    url: jdbc:mysql://localhost:3306/authentication?createDatabaseIfNotExist=true&serverTimezone=UTC&characterEncoding=UTF-8&useSSL=false
    username: root
    password: MySQL04@2020

  jpa:
    hibernate:
      ddl-auto: update